#!/bin/bash

cp xsum.c xsum.c-opt
compile clang-intel; cp xsum-time xsum-time-clang
GCC=-10 compile gcc-intel; cp xsum-time xsum-time-gcc

ed xsum.c <no-opt-script
compile clang-intel; cp xsum-time xsum-time-clang-no-opt
GCC=-10 compile gcc-intel; cp xsum-time xsum-time-gcc-no-opt

cp xsum.c-opt xsum.c
