#!/bin/bash

# Compute shasums of results files, after removing times, and Kahan
# and Float 128 results.  Differences are seen on different systems,
# and with 32 vs. 64 bit, perhaps due to different decimal conversion
# routines for floating point values (that don't produce exact result). 

while test x$1 != x; do
  fgrep -v "Float 128" < $1 | fgrep -v "Double" | fgrep -v "Kahan" | \
    sed "s/time:.*//" | shasum | sed "s/ -/ $1/"
  shift
done
