#!/bin/bash

# Run checks and timing tests, including with Zhu & Hayes method.

TOP=`git rev-parse --show-toplevel`

$TOP/run-checks

$TOP/xsum-time-zhu 10 1 100000000
$TOP/xsum-time-zhu 100 1 10000000
$TOP/xsum-time-zhu 1000 1 1000000
$TOP/xsum-time-zhu 10000 1 100000
$TOP/xsum-time-zhu 100000 1 10000
$TOP/xsum-time-zhu 1000000 1 1000
$TOP/xsum-time-zhu 10000000 1 100
