#!/bin/bash

# Run checks and timing tests.

TOP=`git rev-parse --show-toplevel`

$TOP/run-checks

if [ $# -eq 0 ]; then R=00; else R=$1; fi

$TOP/xsum-time 10 1 1000000$R warm
$TOP/xsum-time 100 1 100000$R warm
$TOP/xsum-time 1000 1 10000$R warm
$TOP/xsum-time 10000 1 1000$R warm
$TOP/xsum-time 100000 1 100$R warm
$TOP/xsum-time 1000000 1 10$R warm
$TOP/xsum-time 10000000 1 1$R warm
