#!/bin/bash

# Run checks and timing tests, including with Zhu & Hayes method.

TOP=`git rev-parse --show-toplevel`

$TOP/run-checks

if [ $# -eq 0 ]; then R=00; else R=$1; fi

$TOP/xsum-time-zhu 10 1 1000000$R warm
$TOP/xsum-time-zhu 100 1 100000$R warm
$TOP/xsum-time-zhu 1000 1 10000$R warm
$TOP/xsum-time-zhu 10000 1 1000$R warm
$TOP/xsum-time-zhu 100000 1 100$R warm
$TOP/xsum-time-zhu 1000000 1 10$R warm
$TOP/xsum-time-zhu 10000000 1 1$R warm
